export const ASIDE_CONTAINER_CLASS = 'aside_container__R9MN6'
export const ASIDE_CONTAINER_EXPANDED_CLASS = 'aside_is_expanded__ghOLS'
export const ASIDE_SHOW_TOOLTIP_CLASS = 'aside_show_tooltip__Ij2rV'
export const ASIDE_CONTENT_TARGET_CLASS = 'aside_content__j2eTE'
export const NAV_WRAPPER_CLASS = 'navigation_bar_section__hDpyD'
