export const NAV_TARGET_ID = 'navigation'
export const NAV_TARGET_CLASS = 'navigator_is_expanded__4Q1h9'
export const NAV_WRAPPER_CLASS = 'navigator_wrapper__ruh6f'
export const HEADER_SECTION_CLASS = 'header_section__iT7rY'
export const HEADER_SHOW_TOOLTIP_CLASS = 'header_show_tooltip__uG4at'
