export const NAV_TARGET_CLASS = 'navigator_is_expanded__4Q1h9'
export const NAV_WRAPPER_CLASS = 'navigator_wrapper__ruh6f'
export const NAV_HEADER_CLASS = 'navigator_header__inwmE'
export const NAV_TITLE_CLASS = 'navigator_title__9RhVJ'
export const NAV_LIST_CLASS = 'navigator_list__cHnuV'
export const NAV_ITEM_CLASS = 'navigator_item__qXlq9'
